# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20170630_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='cource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Cource', verbose_name=b'\xd0\x9a\xd1\x83\xd1\x80\xd1\x81'),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Department', verbose_name=b'\xd0\xa4\xd0\xb0\xd0\xba\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb5\xd1\x82'),
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Group', verbose_name=b'\xd0\x93\xd1\x80\xd1\x83\xd0\xbf\xd0\xb0'),
        ),
    ]
