# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20170702_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cource',
            name='path',
            field=models.CharField(max_length=1, verbose_name=b'\xd0\x9a\xd1\x83\xd1\x80\xd1\x81'),
        ),
        migrations.AlterField(
            model_name='evalution',
            name='appraisal',
            field=models.CharField(max_length=1, verbose_name=b'\xd0\x9e\xd1\x86\xd0\xb5\xd0\xbd\xd0\xba\xd0\xb0'),
        ),
    ]
