# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_evalution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalution',
            name='date',
            field=models.DateField(),
        ),
    ]
