# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20170707_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='cource',
            field=models.ManyToManyField(to='university.Cource'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ManyToManyField(to='university.Department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(to='university.Group'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='university.Subject'),
        ),
    ]
