# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20170915_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name']},
        ),
    ]
