# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_auto_20171102_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(upload_to=b'media/photo'),
        ),
    ]
