# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_auto_20171106_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['-surname']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-surname']},
        ),
    ]
