# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_auto_20180218_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cource',
            field=models.ManyToManyField(to='university.Cource', verbose_name='\u041a\u0443\u0440\u0441'),
        ),
    ]
