# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0019_auto_20180218_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ManyToManyField(to='university.Department', verbose_name='\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='group',
            field=models.ManyToManyField(to='university.Group', verbose_name='\u0413\u0440\u0443\u043f\u0430'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='university.Subject', verbose_name='\u041f\u0440\u0438\u0434\u043c\u0435\u0442'),
        ),
    ]
