# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0020_auto_20180218_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['surname']},
        ),
    ]
