# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0021_auto_20180416_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cource',
            name='path',
            field=models.CharField(max_length=1, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.CharField(max_length=255, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='evalution',
            name='appraisal',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='evalution',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Students', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='evalution',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='evalution',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Teacher', verbose_name='Преподователь'),
        ),
        migrations.AlterField(
            model_name='group',
            name='party',
            field=models.CharField(max_length=255, verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='students',
            name='cource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Cource', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Department', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Group', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='photo_student'),
        ),
        migrations.AlterField(
            model_name='students',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='matter',
            field=models.CharField(max_length=255, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
    ]
